"$schema" = "https://developers.cloudflare.com/workers/wrangler/config-schema.json"

name = "timothy-portfolio-cms-auth"
main = "src/index.js"
compatibility_date = "2026-08-06"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://timothykim.tkimify.com"
ALLOWED_SITE_DOMAIN = "timothykim.tkimify.com"
GITHUB_REPO_PRIVATE = "0"
